/*
 * priorityLevels.h
 *
 *  Created on: Jan 2, 2018
 *      Author: tbiberdorf
 */

#ifndef BOARD_PRIORITYLEVELS_H_
#define BOARD_PRIORITYLEVELS_H_

/**
 * Priority Levels for all RTOS tasks being Run
 */
#define NET_CABLE_TASK_PRIORITY (2)
#define CLI_THREAD_PRIORITY (2)
#define ADC0_TASK_PRIORITY (configMAX_PRIORITIES - 1)
#define HTTPD_TREAD_PRIORITY (2)
#define TCPIP_THREAD_PRIORITY (configMAX_PRIORITIES - 2)
#define UDP_TASK_PRIORITY (1)
#define UDP_TEST_TASK_PRIORITY (1)

#define NET_CABLE_TASK_STACK_SIZE (configMINIMAL_STACK_SIZE*10)
#define AD0_TASK_STACK_SIZE (configMINIMAL_STACK_SIZE*10)
#define CLI_THREAD_STACKSIZE (configMINIMAL_STACK_SIZE*10)
#define HTTPD_TREAD_STACKSIZE (3000 )
#define UDP_TASK_STACK_SIZE (configMINIMAL_STACK_SIZE*10)


#define ADC0_IRQ_PRIORITY_LEVEL (configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY)
#define ADC1_IRQ_PRIORITY_LEVEL (configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY)

#define MCP3911_SPI0_IRQ_PRIORITY_LEVEL (configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY)
#define MCP3911_GPIOC_DATA_READY_IRQ_PRIORITY_LEVEL (configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY +1)

#define PILOT_CNTL_IRQ_PRIORITY_LEVEL (configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY+3)
/**
 * IRQ Priority Levels
 */

#endif /* BOARD_PRIORITYLEVELS_H_ */
